#!/usr/bin/env python3
"""Regenerate game/Arcade/vendor_pb.h from game/Arcade/vendor.proto.

The arcade SDK needs the vendor schema as a serialized
google.protobuf.FileDescriptorSet (InitRequest.vendor_descriptor_set). We embed
those bytes in the executable so the game has no runtime dependency on protoc
or on a .pb file next to the binary.

Requires `protoc` on PATH (Ubuntu: apt install protobuf-compiler).
"""
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
SDK_PROTO = os.path.join(HERE, '..', '..', 'ThirdParty', 'arcade_sdk', 'proto')
SRC = os.path.join(HERE, 'vendor.proto')
OUT = os.path.join(HERE, 'vendor_pb.h')


def main():
    with tempfile.TemporaryDirectory() as tmp:
        pb = os.path.join(tmp, 'vendor.pb')
        cmd = ['protoc', '-I', HERE, '-I', SDK_PROTO, '--include_imports',
               '--descriptor_set_out=' + pb, SRC]
        print(' '.join(cmd))
        subprocess.check_call(cmd)
        with open(pb, 'rb') as f:
            data = f.read()

    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append('\t' + ', '.join('0x%02x' % b for b in chunk) + ',')

    with open(OUT, 'w', newline='\n') as f:
        f.write('// Generated by gen_vendor_pb.py from vendor.proto; do not edit.\n')
        f.write('// Serialized google.protobuf.FileDescriptorSet (with imports) for the\n')
        f.write('// arcade SDK InitRequest.vendor_descriptor_set field.\n')
        f.write('#ifndef __ARCADE_VENDOR_PB_H__\n#define __ARCADE_VENDOR_PB_H__\n\n')
        f.write('static const unsigned char arcade_vendor_pb[] = {\n')
        f.write('\n'.join(lines))
        f.write('\n};\n')
        f.write('static const unsigned int arcade_vendor_pb_len = %d;\n\n' % len(data))
        f.write('#endif\n')
    print('wrote %s (%d bytes)' % (OUT, len(data)))


if __name__ == '__main__':
    sys.exit(main())
